# FROM ubuntu:22.04

# RUN apt update && apt-get install -y curl
# RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

# RUN apt update && apt-get install -y nodejs
FROM node:latest
RUN mkdir /app/

WORKDIR /app/
COPY package.json /app/
RUN npm config set legacy-peer-deps true && npm install

COPY . /app/

ENTRYPOINT ["npm", "start"]
